# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "caylent-hugo-theme"
license = "MIT"
licenselink = "https://github.com/caylent/caylent-hugo-theme/blob/master/LICENSE.md"
description = "Simple theme"
homepage = "https://github.com/caylent/caylent-hugo-theme/"
tags = ["responsive", "simple"]
features = ["Responsive", "Thumbnail", "JSON-LD"]
min_version = "0.75.1"
mainSections = [ "post" ]

[author]
  name = "Caylent inc"
  homepage = "https://caylent.com"

# If porting an existing theme
[original]
  name = "Daisuke KONISHI"
  homepage = "https://daisukekonishi.com"
  repo = "https://github.com/dsk52/minimage/"
